[manager]
show_hidden = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
	{ name = "*.{toml,lua,conf,py,go,rs,sh,json,txt,html}", use = "edit" },
	{ name = ".bash*", use = "edit" },
]

[layou]
ratios = [ 1, 2, 5 ]
